name: CI Build and Test

on:
  push:
    branches: [ hotfix_plugboard, main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake build-essential
    
    - name: Check versions
      run: |
        echo "CMake version:"
        cmake --version
        echo "G++ version:"
        g++ --version
    
    - name: Configure project
      run: cmake -B build -S .
    
    - name: Build project
      run: cmake --build build --verbose
    
    - name: List build directory
      run: |
        echo "Build directory contents:"
        ls -la build/
        echo "Test directory contents:"
        ls -la build/tests/
    
    - name: Run tests with CTest
      working-directory: build
      run: ctest --output-on-failure -V
    
    - name: Run test executables directly
      working-directory: build/tests
      run: |
        echo "Running all_tests..."
        ./all_tests
        echo ""
        echo "Running plugboard_test..."
        ./plugboard_test
        echo ""
        echo "Running rotor_test..."
        ./rotor_test
        echo ""
        echo "Running enigma_machine_test..."
        ./enigma_machine_test
    
    - name: Test main executable
      working-directory: build
      run: |
        echo "Testing enigma executable..."
        echo "5" | ./enigma || echo "Program exited successfully"