name: Simple CI

on:
  push:
    branches: [ setup_git_actions ]

jobs:
  build:
    runs-on: ubuntu-22.04  # This has CMake 3.22 by default
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake build-essential
    
    - name: Build
      run: |
        cmake -B build
        cmake --build build
    
    - name: Test
      run: |
        cd build
        ctest --output-on-failure