name: Quick Test

on:
  push:
    branches: [ setup_git_actions ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y g++ cmake
    
    - name: Build
      run: |
        cmake -B build
        cmake --build build
    
    - name: Run a test
      run: ./build/tests/all_tests